### ISSUE TITLE
Plugin is not compatible with webpack 5 new entry object

### ISSUE THREAD

**Issue by ryanelian** [WebHotelier/webpack-fast-refresh#3]
Webpack 5 introduces new entry configuration: https://webpack.js.org/configuration/entry-context/#entry-descriptor

This entry configuration can be used for renaming module imported into a file, for example:

```js
entry: {
    bundle: {
      import: ['./a.js', './b.js', './c.js'],
      filename: 'mybundle.js'
    }
  }
```

Unfortunately, webpack-fast-refresh is not compatible with this new entry descriptor object:

```
Error: Failed to parse the Webpack `entry` object!
    at injectRefreshEntry (D:\VS\instapack\node_modules\.pnpm\registry.npmjs.org\@webhotelier\webpack-fast-refresh\2.0.0\node_modules\@webhotelier\webpack-fast-refresh\src\helpers\injectRefreshEntry.js:41:9)
    at D:\VS\instapack\node_modules\.pnpm\registry.npmjs.org\@webhotelier\webpack-fast-refresh\2.0.0\node_modules\@webhotelier\webpack-fast-refresh\src\helpers\injectRefreshEntry.js:28:19
    at Array.reduce (<anonymous>)
    at injectRefreshEntry (D:\VS\instapack\node_modules\.pnpm\registry.npmjs.org\@webhotelier\webpack-fast-refresh\2.0.0\node_modules\@webhotelier\webpack-fast-refresh\src\helpers\injectRefreshEntry.js:25:42)
    at D:\VS\instapack\node_modules\.pnpm\registry.npmjs.org\@webhotelier\webpack-fast-refresh\2.0.0\node_modules\@webhotelier\webpack-fast-refresh\src\helpers\injectRefreshEntry.js:28:19
    at Array.reduce (<anonymous>)
    at injectRefreshEntry (D:\VS\instapack\node_modules\.pnpm\registry.npmjs.org\@webhotelier\webpack-fast-refresh\2.0.0\node_modules\@webhotelier\webpack-fast-refresh\src\helpers\injectRefreshEntry.js:25:42)
    at ReactRefreshPlugin.apply (D:\VS\instapack\node_modules\.pnpm\registry.npmjs.org\@webhotelier\webpack-fast-refresh\2.0.0\node_modules\@webhotelier\webpack-fast-refresh\src\index.js:22:30)
    at createCompiler (D:\VS\instapack\node_modules\.pnpm\registry.npmjs.org\webpack\5.0.0-beta.16_webpack@5.0.0-beta.16\node_modules\webpack\lib\webpack.js:70:12)
```

**Comment by apostolos** [comment]
Thanks for the report. Will fix in next version (unfortunately a breaking release, will require some config changes).

**Comment by apostolos** [comment]
@ryanelian We've released a new version that adds support for descriptor entries. 👍
https://github.com/WebHotelier/webpack-fast-refresh/releases/tag/v5.0.0

You'll need to make sure you are running `webpack@v5.0.0-beta.15` or later and make the changes that are detailed in the [README](https://github.com/WebHotelier/webpack-fast-refresh/blob/master/README.md).

**Comment by ryanelian** [comment]
That was fast, thank you!

Tested the new package using [my build tool](https://github.com/ryanelian/instapack) on a simple project, it works.
